[camera]
look_from = [250.5, 250.5, -800]
look_at = [250.5, 250.5, 500]
# view_up = [0, 0.5, 0]
image_width = 600
aspect_ratio = 1
vertical_fov = 60
# defocus_angle = 0
# focus_dist = 10
samples_per_pixel = 100
max_ray_range = 2000
# max_depth = 50
background_color = [0, 0, 0]

[[objects]]
type = "quad"
q = [500, 0, 0]
u = [0, 500, 0]
v = [0, 0, 500]
[objects.material]
type = "lambertian"
[objects.material.texture]
type = "solid"
color = [0.8, 0.1, 0.1]

[[objects]]
type = "quad"
q = [0, 500, 0]
u = [500, 0, 0]
v = [0, 0, 500]
[objects.material]
type = "lambertian"
[objects.material.texture]
type = "solid"
color = [0.8, 0.8, 0.8]

[[objects]]
type = "quad"
q = [0, 0, 500]
u = [500, 0, 0]
v = [0, 500, 0]
[objects.material]
type = "lambertian"
[objects.material.texture]
type = "solid"
color = [0.8, 0.8, 0.8]

[[objects]]
type = "quad"
q = [0, 0, 0]
u = [500, 0, 0]
v = [0, 0, 500]
[objects.material]
type = "lambertian"
[objects.material.texture]
type = "solid"
color = [0.8, 0.8, 0.8]

[[objects]]
type = "quad"
q = [0, 0, 0]
u = [0, 500, 0]
v = [0, 0, 500]
[objects.material]
type = "lambertian"
[objects.material.texture]
type = "solid"
color = [0.1, 0.8, 0.1]

[[objects]]
type = "quad"
q = [100, 490, 100]
u = [300, 0, 0]
v = [0, 0, 300]
[objects.material]
type = "diffuse_light"
color = [1, 1, 1]
strength = 5

[[objects]]
type = "translate"
offset = [350, 165, 365]
[objects.instance]
type = "rotate_y"
angle = 25
[objects.instance.instance]
type = "cube"
a = [-82.5, -165, -82.5]
b = [82.5, 165, 82.5]
[objects.instance.instance.material]
type = "lambertian"
[objects.instance.instance.material.texture]
type = "solid"
color = [0.8, 0.8, 0.8]

[[objects]]
type = "translate"
offset = [150, 82.5, 215]
[objects.instance]
type = "rotate_y"
angle = -25
[objects.instance.instance]
type = "cube"
a = [-82.5, -82.5, -82.5]
b = [82.5, 82.5, 82.5]
[objects.instance.instance.material]
type = "lambertian"
[objects.instance.instance.material.texture]
type = "solid"
color = [0.8, 0.8, 0.8]

[[objects]]
type = "constant_medium"
density = 0.01
[objects.texture]
type = "solid"
color = [1, 1, 1]
[objects.boundary]
type = "cube"
a = [0, 0, 0]
b = [1000, 50, 1000]
